//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingoOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bingo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bingo()
        {
            this.Cartela = new HashSet<Cartela>();
            this.OrdemSorteio = new HashSet<OrdemSorteio>();
        }
    
        public int BingoId { get; set; }
        public string Descricao { get; set; }
        public int Status { get; set; }
        public string MotivoCancelamento { get; set; }
        public Nullable<System.DateTime> DataCancelamento { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public System.DateTime DataRealizacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cartela> Cartela { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemSorteio> OrdemSorteio { get; set; }
    }
}
