//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingoOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorteios
    {
        public int SorteioId { get; set; }
        public int CartelaId { get; set; }
        public int OrdemSorteioId { get; set; }
        public int QuantidadeAcertos { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Cartela Cartela { get; set; }
        public virtual OrdemSorteio OrdemSorteio { get; set; }
    }
}
